#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Create release

on:
  schedule:
    - cron: 0 8 */3 * *
  watch:
    types: started
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/build-openwrt.yml'
      - '.config'


jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Generate tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d-%H%M%S")"
      env:
        TZ: Asia/Shanghai

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.all_TOKEN }}
      with:
        tag_name: ${{ env.all_TAG }}
        body: 🚀 Automated build | 自动编译
