#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================
name: Lean-Lienol-x64-simple-ssr


on:

  schedule:
    - cron: 0 20 * * *

#  release:
#    types: published

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/Lean-Lienol-x64-simple-ssr.yml'
      - 'Lean-Lienol-x64-simple-ssr'

  watch:
    types: [started]


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FIRMWARE_NAME: Lean-Lienol-x64-simple-ssr
  CONFIG_FILE: Lean-Lienol-x64-simple-ssr
  DIY_SH: diy.sh
  TARGET: x86
  SUBTARGET: 64
  SSH_ACTIONS: false
  Gzip_file: true
  UPLOAD_BIN_DIR: false
  UPLOAD_ZIP: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

  
  # FREE_UP_DISK: true
  # UPLOAD_EXT4_IMAGES: true
  # UPLOAD_SQUASHFS_IMAGES: true
  # UPLOAD_ROOTFS: true
  # UPLOAD_TMP_LINK: true


jobs:
  
  build:
    
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h
    
      - name: Clone source code
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_SH
          cd openwrt
          ../$DIY_SH

      - name: Extract Gz Files
        id: extract
        run: |
          PWD
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          PWD
         
      - name: Organize files
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true'
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success"
     
      - name: Upload zip
        id: upload_zip
        run: |
          rm -rf ./release/
          mkdir -p ./release/
          pwd
    
      - name: Upload firmware directory
        id: upload_firmware
        run: |
          cd ${{ env.FIRMWARE }}
          PWD

