#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================
name: Lean-Lienol-x64-simple


on:

#  schedule:
#    - cron: 0 20 * * *

#  release:
#    types: published

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/Lean-Lienol-x64-simple.yml'
#      - 'Lean-Lienol-x64-simple'

  watch:
    types: [started]


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FIRMWARE_NAME: Lean-Lienol-x64-simple
  CONFIG_FILE: Lean-Lienol-x64-simple
  DIY_SH: diy.sh
  TARGET: x86
  SUBTARGET: 64
  SSH_ACTIONS: false
  Gzip_file: true
  UPLOAD_ZIP: true
  UPLOAD_ALL: false
  UPLOAD_ORGANIZE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

  
  # FREE_UP_DISK: true
  # UPLOAD_EXT4_IMAGES: true
  # UPLOAD_SQUASHFS_IMAGES: true
  # UPLOAD_ROOTFS: true
  # UPLOAD_TMP_LINK: true


jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1000000
          
      - name: Set Date
        run: |
           date=$(TZ=UTC-8 date +"%Y.%m.%d-%H%M%S")
           echo "::set-env name=DATE::$date"
           
      - name: new name
        run : |
           firmware_name="${FIRMWARE_NAME}-${DATE}"
           release_name="${DATE}-${FIRMWARE_NAME}"
           echo "::set-env name=NEW_NAME::$firmware_name"
           echo "::set-env name=RELEASE_NAME::$release_name"
           
           
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Clone source code
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_SH
          cd openwrt
          ../$DIY_SH

      - name: Download package
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s
          echo "::set-output name=status::success"
      
      - name: Extract Gz Files
        id: extract
        if: steps.compile.outputs.status == 'success'
        run: |
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          gzip -qd *.img.gz  || true
          rm -f *.img.gz
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success" 
          
      - name: Rename file
        id: rename
        run: |
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          for i in openwrt*; do mv -f $i `echo $i | sed "s/^openwrt-$TARGET-$SUBTARGET/${NEW_NAME}/"`; done
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success"
      
#      - name: SSH connection to Actions
#        uses: owlboy-lin/debugger-action@master
#        if: env.SSH_ACTIONS == 'true'      
    
      - name: Gz Files
        id: Gzip_file
        if: steps.rename.outputs.status == 'success' && env.Gzip_file == 'true' 
        run: |
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          gzip *.img || true
          # rm -f *.img
          echo "::set-output name=status::success"
  
      - name: Generate Sha256sum File For Images
        run: |
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          mv sha256sums sha256sums.orig
          sha256sum *.* > sha256sums
         
      - name: Organize files
        id: organize
        if: env.UPLOAD_ORGANIZE == 'false' 
        run: |
          # cd openwrt/bin/targets/*/*
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          rm -rf packages
          echo "::set-output name=status::success"

      - name: Upload firmware directory
        id: upload_firmware
        uses: actions/upload-artifact@master
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ env.NEW_NAME }}
          path: ${{ env.FIRMWARE }}

      - name: Upload zip
        id: upload_zip
        run: |
          cd openwrt
          rm -rf ./release/
          mkdir -p ./release/
          zip -r release/${{ env.NEW_NAME }}.zip bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/* || true
          cd release
          echo "::set-env name=RELEASE::$PWD"
          echo "::set-output name=status::success"   

      - name: SSH connection to Actions
        uses: owlboy-lin/debugger-action@master
        if: env.SSH_ACTIONS == 'true'      
        
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.all_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: 自动发布 ${{ env.NEW_NAME }}
          files: ${{ env.RELEASE }}/*
